<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getAdminOrderDetail, getAdminOrders, updateOrderStatus } from '../services/admin-order'
import type { AdminOrderData, OrderDetailData } from '../types/api'
import { getOrderStatusLabel } from '../utils/order-status'

const orders = ref<AdminOrderData[]>([])
const selectedOrder = ref<OrderDetailData | null>(null)
const pageNo = ref(1); const total = ref(0); const status = ref<number | undefined>()
const loading = ref(true); const actionId = ref<number | null>(null); const errorMessage = ref('')
const formatPrice = (cents: number) => `¥${(cents / 100).toFixed(2)}`
async function load() { loading.value = true; errorMessage.value = ''; try { const result = await getAdminOrders(pageNo.value, status.value); orders.value = result.records; total.value = result.total } catch (e) { errorMessage.value = e instanceof Error ? e.message : '管理订单查询失败' } finally { loading.value = false } }
async function detail(order: AdminOrderData) { if (selectedOrder.value?.orderId === order.orderId) return (selectedOrder.value = null); try { selectedOrder.value = await getAdminOrderDetail(order.orderId) } catch (e) { errorMessage.value = e instanceof Error ? e.message : '订单详情查询失败' } }
async function advance(order: AdminOrderData) { if (order.status >= 4 || actionId.value) return; actionId.value = order.orderId; errorMessage.value = ''; try { await updateOrderStatus(order.orderId, order.status + 1); await load() } catch (e) { errorMessage.value = e instanceof Error ? e.message : '订单状态更新失败' } finally { actionId.value = null } }
onMounted(load)
</script>
<template><section class="reservation-view"><div class="reservation-heading"><p class="eyebrow">管理端订单</p><h1>订单工作台</h1><p>查看订单并按后端状态机推进制作流程。</p></div><div class="admin-toolbar"><label>状态<select v-model="status" @change="pageNo = 1; load()"><option :value="undefined">全部</option><option :value="1">已下单</option><option :value="2">制作中</option><option :value="3">已上齐</option><option :value="4">已完成</option><option :value="5">已取消</option></select></label></div><p v-if="errorMessage" class="feedback feedback-error" role="alert">{{ errorMessage }}</p><p v-if="loading" class="feedback" role="status">正在查询订单...</p><p v-else-if="orders.length === 0" class="feedback" role="status">当前没有订单。</p><div v-else class="reservation-list"><article v-for="order in orders" :key="order.orderId" class="reservation-card"><div class="reservation-card-heading"><div><strong>{{ order.orderNo }}</strong><span>{{ order.tableNo }} · {{ order.createTime }}</span></div><span class="reservation-status">{{ getOrderStatusLabel(order.status) }}</span></div><p class="reservation-time">{{ formatPrice(order.totalAmount) }}</p><div class="reservation-actions"><button class="secondary-button" type="button" @click="detail(order)">{{ selectedOrder?.orderId === order.orderId ? '收起详情' : '详情' }}</button><button v-if="order.status >= 1 && order.status <= 3" class="primary-outline-button" type="button" :disabled="actionId === order.orderId" @click="advance(order)">{{ actionId === order.orderId ? '更新中...' : order.status === 1 ? '开始制作' : order.status === 2 ? '标记已上齐' : '完成订单' }}</button></div><dl v-if="selectedOrder?.orderId === order.orderId" class="reservation-detail"><div v-for="item in selectedOrder.items" :key="item.dishId"><dt>{{ item.dishName }} × {{ item.quantity }}</dt><dd>{{ formatPrice(item.amount) }}</dd></div></dl></article></div><p class="feedback">第 {{ pageNo }} 页，共 {{ total }} 条</p><div class="pagination-actions"><button class="secondary-button" type="button" :disabled="pageNo <= 1 || loading" @click="pageNo--; load()">上一页</button><button class="secondary-button" type="button" :disabled="pageNo * 10 >= total || loading" @click="pageNo++; load()">下一页</button></div></section></template>
